/**
 * Created by Web on 2017/1/10.
 */
angular.module('myModule', ['ionic'])
  .config(function($stateProvider,$urlRouterProvider){
    $stateProvider
      .state('start',{
        url:'/myStart',
        templateUrl:'tpl/start.html'
      })
      .state('main',{
        url:'/myMain',
        templateUrl:'tpl/main.html',
        controller:'mainCtrl'
      })
      .state('order',{
        url:'/myOrder/:id',
        templateUrl:'tpl/order.html',
        controller:'orderCtrl'
      })
      .state('personorder',{
        url:'/myPersonorder',
        templateUrl:'tpl/myorder.html',
        controller:'personorderCtrl'
      })
      .state('detail',{
        url:'/myDetail/:id',
        templateUrl:'tpl/detail.html',
        controller:'detailCtrl'
      })
    $urlRouterProvider.otherwise('myStart')
  })
  .controller('myCtrl',['$scope','$state',function($scope,$state){
    $scope.jump=function(state,args){
      $state.go(state,args)
    }
  }])
  .controller('mainCtrl',['$scope','$http',function($scope,$http){
    $scope.inputTxt={kw:''};
    $http.get('data/dish_getbypage.php?start=0')
      .success(function(data){
        console.log(data)
        $scope.dishList=data;
      })
    $scope.hasMore=true;
    $scope.loadMore=function(){
      $http
        .get('data/dish_getbypage.php?start='+$scope.dishList.length)
        .success(function(data){
          if(data.length<5){
            $scope.hasMore=false;
          }
          $scope.dishList=$scope.dishList.concat(data);
          $scope.$broadcast('scroll.infiniteScrollComplete');
        })
    }
    $scope.$watch('inputTxt.kw',function(){
      console.log($scope.inputTxt.kw)
      if($scope.inputTxt.kw){
        $http
          .get('data/dish_getbykw.php?kw='+$scope.inputTxt.kw)
          .success(function(data){
            $scope.dishList=data;
          })
      }
    })
  }])
  .controller('detailCtrl',['$scope','$http','$stateParams',
    function($scope,$http,$stateParams){
    $http
      .get('data/dish_getbyid.php?id='+$stateParams.id)
      .success(function(data){
        console.log(data[0])
        $scope.dishDetail=data[0]
      })
  }])
  .controller('orderCtrl',['$scope','$http','$stateParams','$httpParamSerializerJQLike',
    function($scope,$http,$stateParams,$httpParamSerializerJQLike){
      $scope.order={'did':$stateParams.id};
      $scope.submitOrder=function(){
        console.log($scope.order);
        var args=$httpParamSerializerJQLike($scope.order);
        $http.get('data/order_add.php?'+args)
          .success(function(data){
            if(data[0].msg=='succ'){
              sessionStorage.setItem('phone',$scope.order.phone);
              $scope.succMsg="下单成功，订单编号为"+data[0].oid;
            }else{
              $scope.errMsg="下单失败";
            }
          })
      }
    }])
  .controller('personorderCtrl',['$scope','$http',
    function($scope,$http){
      var phone=sessionStorage.getItem('phone')
      $http
        .get('data/order_getbyphone.php?phone='+phone)
        .success(function(data){
          console.log(data)
          $scope.orderList=data;
        })
    }])
